namespace PlatynUI.Platform.X11.Interop.XCB;

[NativeTypeName("unsigned int")]
public enum xcb_ewmh_moveresize_direction_t : uint
{
    XCB_EWMH_WM_MOVERESIZE_SIZE_TOPLEFT = 0,
    XCB_EWMH_WM_MOVERESIZE_SIZE_TOP = 1,
    XCB_EWMH_WM_MOVERESIZE_SIZE_TOPRIGHT = 2,
    XCB_EWMH_WM_MOVERESIZE_SIZE_RIGHT = 3,
    XCB_EWMH_WM_MOVERESIZE_SIZE_BOTTOMRIGHT = 4,
    XCB_EWMH_WM_MOVERESIZE_SIZE_BOTTOM = 5,
    XCB_EWMH_WM_MOVERESIZE_SIZE_BOTTOMLEFT = 6,
    XCB_EWMH_WM_MOVERESIZE_SIZE_LEFT = 7,
    XCB_EWMH_WM_MOVERESIZE_MOVE = 8,
    XCB_EWMH_WM_MOVERESIZE_SIZE_KEYBOARD = 9,
    XCB_EWMH_WM_MOVERESIZE_MOVE_KEYBOARD = 10,
    XCB_EWMH_WM_MOVERESIZE_CANCEL = 11,
}
