# This file was generated by PythonNetStubGenerator
# mypy: ignore-errors
import typing, abc

class IIdentity(typing.Protocol):
    @property
    def AuthenticationType(self) -> typing.Optional[str]: ...
    @property
    def IsAuthenticated(self) -> bool: ...
    @property
    def Name(self) -> typing.Optional[str]: ...

class IPrincipal(typing.Protocol):
    @property
    def Identity(self) -> typing.Optional[IIdentity]: ...
    @abc.abstractmethod
    def IsInRole(self, role: str) -> bool: ...

class PrincipalPolicy(typing.SupportsInt):
    @typing.overload
    def __init__(self, value: int) -> None: ...
    @typing.overload
    def __init__(self, value: int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...

    # Values:
    UnauthenticatedPrincipal: PrincipalPolicy  # 0
    NoPrincipal: PrincipalPolicy  # 1
    WindowsPrincipal: PrincipalPolicy  # 2

class TokenImpersonationLevel(typing.SupportsInt):
    @typing.overload
    def __init__(self, value: int) -> None: ...
    @typing.overload
    def __init__(self, value: int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...

    # Values:
    None_: TokenImpersonationLevel  # 0
    Anonymous: TokenImpersonationLevel  # 1
    Identification: TokenImpersonationLevel  # 2
    Impersonation: TokenImpersonationLevel  # 3
    Delegation: TokenImpersonationLevel  # 4
