import typing, clr, abc

class tagPOINT:
    x: int
    y: int

class tagRECT:
    bottom: int
    left: int
    right: int
    top: int

class IUIAutomationElement(typing.Protocol):
    @property
    def CurrentAcceleratorKey(self) -> str: ...
    @property
    def CurrentAccessKey(self) -> str: ...
    @property
    def CurrentAriaProperties(self) -> str: ...
    @property
    def CurrentAriaRole(self) -> str: ...
    @property
    def CurrentAutomationId(self) -> str: ...
    @property
    def CurrentBoundingRectangle(self) -> tagRECT: ...
    @property
    def CurrentClassName(self) -> str: ...
    @property
    def CurrentControlType(self) -> int: ...
    @property
    def CurrentCulture(self) -> int: ...
    @property
    @property
    def CurrentFrameworkId(self) -> str: ...
    @property
    def CurrentFullDescription(self) -> str: ...
    @property
    def CurrentHasKeyboardFocus(self) -> int: ...
    @property
    def CurrentHeadingLevel(self) -> int: ...
    @property
    def CurrentHelpText(self) -> str: ...
    @property
    def CurrentIsContentElement(self) -> int: ...
    @property
    def CurrentIsControlElement(self) -> int: ...
    @property
    def CurrentIsDataValidForForm(self) -> int: ...
    @property
    def CurrentIsDialog(self) -> int: ...
    @property
    def CurrentIsEnabled(self) -> int: ...
    @property
    def CurrentIsKeyboardFocusable(self) -> int: ...
    @property
    def CurrentIsOffscreen(self) -> int: ...
    @property
    def CurrentIsPassword(self) -> int: ...
    @property
    def CurrentIsPeripheral(self) -> int: ...
    @property
    def CurrentIsRequiredForForm(self) -> int: ...
    @property
    def CurrentItemStatus(self) -> str: ...
    @property
    def CurrentItemType(self) -> str: ...
    @property
    def CurrentLabeledBy(self) -> "IUIAutomationElement": ...
    @property
    def CurrentLandmarkType(self) -> int: ...
    @property
    def CurrentLevel(self) -> int: ...
    @property
    def CurrentLocalizedControlType(self) -> str: ...
    @property
    def CurrentLocalizedLandmarkType(self) -> str: ...
    @property
    def CurrentName(self) -> str: ...
    @property
    def CurrentNativeWindowHandle(self) -> int: ...
    @property
    def CurrentOptimizeForVisualContent(self) -> int: ...
    @property
    def CurrentPositionInSet(self) -> int: ...
    @property
    def CurrentProcessId(self) -> int: ...
    @property
    def CurrentProviderDescription(self) -> str: ...
    @property
    def CurrentSizeOfSet(self) -> int: ...
    @abc.abstractmethod
    def GetClickablePoint(self, clickable: clr.Reference[tagPOINT]) -> int: ...
    @abc.abstractmethod
    def GetCurrentMetadataValue(self, targetId: int, metadataId: int) -> typing.Any: ...
    @abc.abstractmethod
    def GetCurrentPattern(self, patternId: int) -> typing.Any: ...
    @abc.abstractmethod
    def GetCurrentPropertyValue(self, propertyId: int) -> typing.Any: ...
    @abc.abstractmethod
    def GetCurrentPropertyValueEx(self, propertyId: int, ignoreDefaultValue: int) -> typing.Any: ...
    @abc.abstractmethod
    def SetFocus(self) -> None: ...
    @abc.abstractmethod
    def ShowContextMenu(self) -> None: ...
